version: '3.8'

services:
  broker-mqtt:
    image: eclipse-mosquitto:latest
    container_name: broker-mqtt
    hostname: broker-mqtt
    networks:
      zone-d-dmz:
        ipv4_address: 10.0.0.20
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/acl.conf:/mosquitto/config/acl.conf:ro
      - ../certificates/certs:/mosquitto/config/certs:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influxdb
    networks:
      zone-d-dmz:
        ipv4_address: 10.0.0.40
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass123
      - DOCKER_INFLUXDB_INIT_ORG=usine-iot
      - DOCKER_INFLUXDB_INIT_BUCKET=firewall-logs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123456
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    hostname: grafana
    networks:
      zone-d-dmz:
        ipv4_address: 10.0.0.30
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../certificates/certs:/etc/grafana/certs:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=http://10.0.0.30:3000
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    depends_on:
      - influxdb
    restart: unless-stopped

  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    hostname: ldap
    networks:
      zone-d-dmz:
        ipv4_address: 10.0.0.10
    ports:
      - "636:636"
    environment:
      - LDAP_ORGANISATION=UsineIoT
      - LDAP_DOMAIN=usine.local
      - LDAP_ADMIN_PASSWORD=ldapadmin
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    restart: unless-stopped

networks:
  zone-d-dmz:
    external: true

volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-data:
  grafana-data:
  ldap-data:
  ldap-config: