version: '3.8'

services:
  admin:
    image: alpine:latest
    container_name: admin
    hostname: admin
    command: |
      sh -c "
      apk add --no-cache openssh curl bash mosquitto-clients
      
      ssh-keygen -A
      echo 'root:admin123' | chpasswd
      
      echo 'Admin machine demarree'
      echo 'SSH: root@admin123'
      
      /usr/sbin/sshd -D
      "
    networks:
      zone-b-admin:
        ipv4_address: 192.168.20.10
    ports:
      - "2222:22"
    restart: unless-stopped

networks:
  zone-b-admin:
    external: true