# ! Config non sécurisée (test)
[[servers]]
host = "10.0.0.10"     # L'IP de ton conteneur LDAP définie dans ton docker-compose
port = 389             #  !!!!!!!!!!!
use_ssl = false        #  !!!!!!!!!!!
start_tls = false
ssl_skip_verify = true #  !!!!!!!!!!!

# Utilisateur
bind_dn = "cn=admin,dc=usine,dc=local"
bind_password = "adminldap"

# Filtre de recherche des utilisateurs pour trouver les membres du groupe peaple dans l'annuaire LDAP *fichier users.ldif
search_filter = "(cn=%s)"
search_base_dns = ["ou=People,dc=usine,dc=local"]

# Format d'enregistrement des utilisateurs dans l'annuaire LDAP
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"