verbose_logging = true
[[servers]]
host = "ldap"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
root_ca_cert = "/etc/grafana/certs/ca.crt"
bind_dn = "cn=admin,dc=usine,dc=local"
bind_password = "adminldap"
search_base_dns = ["ou=People,dc=usine,dc=local"]
search_filter = "(uid=%s)"
[servers.attributes]
name = "givenName"      # Pedro
surname = "sn"          # Martins
username = "uid"        # pedro
email = "mail"          # pedro@usine.local
[[servers.group_mappings]]
group_dn = "ou=People,dc=usine,dc=local"
org_role = "Admin"
# org_id = 1